language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# add environment variable
env:
  - DATABASE_URL="postgres://yaddqlhbmweddl:SxBfLvKcO9Vj2b3tcFLYvLcv9m@ec2-54-243-47-46.compute-1.amazonaws.com:5432/d520svb6jevb35" COOKIE_SECRET="password"
# command to run tests
script: cd json_api && pytest

addons:
  sauce_connect:
    username: "Sharabesh"
    access_key: "42bc2c2b-f383-4e18-b530-5d85c203101d"


