version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 json_api/brainspell.py 
    volumes:
      - .:/brainspell-neo
    ports:
      - "5000:5000"
    depends_on:
      - db