version: '2'
services:
#  db:
#     image: postgres:9.6
#     ports:
#         - "5433:5432"
#     environment:
#         - POSTGRES_PASSWORD=docker
#         - POSTGRES_DB=docker
#         - POSTGRES_USER=docker
     #volumes:
         # Creates trouble unless we make it world-writable or play tricks to
         # match the group or user id inside and outside the container.
         # By default, some Docker magic will create an external volume
         # somewhere...
     #    - ./postgres/data:/docker-entrypoint-initdb.d
  web:
    build: main

    ports:
      - "5000:5000"
#    depends_on:
#      - db
