version: '2'
services:
  db:
     build: postgres
     ports:
         - "5432:5432"
     environment:
         POSTGRES_PASSWORD: docker
         POSTGRES_DB: docker
     volumes:
         # Creates trouble unless we make it world-writable or play tricks to
         # match the group or user id inside and outside the container.
         # By default, some Docker magic will create an external volume
         # somewhere...
         - ./postgres/data:/docker-entrypoint-initdb.d
#  web:
#    build: brainspell
#    volumes:
#      - .:/brainspell-neo
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
